feign:
  url:
    prefix: http://localhost:8080/target_server # DemoFeignClient?? ??? url prefix ?
  client:
    config:
      default:
        connectTimeout: 1000
        readTimeout: 3000
        loggerLevel: NONE
      demo-client: # DemoFeignClient?? ??? Client ?? ?
        connectTimeout: 1000
        readTimeout: 10000
        loggerLevel: HEADER  # ??? ??? ?? FeignCustomLogger -> Logger.Level logLevel ??? ???
#logging:
#  level:
#    ROOT: DEBUG